import unittest

from multiplicity.crypto.protocol import (
    ALICE_LABEL,
    AUTHENTICATION_TAG_LENGTH,
    BOB_LABEL,
    BOOTSTRAP_MESSAGE,
    CLASSICAL_MESSAGE,
    DEFAULT_SALT,
    MAX_PAYLOAD_LENGTH,
    VERSION,
    AeadReplayError,
    AuthenticationError,
    DirectionalAead,
    DirectionalKeys,
    Frame,
    ProtocolAbortError,
    ProtocolReceiver,
    SenderSequenceRegistry,
    StrictSequenceState,
    TranscriptChain,
    build_nonce,
    compute_hmac,
    compute_transcript if False else compute_transcript,
)
